[package]
name = "tm"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.1"
crossbeam = "0.8"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "time"] }
sysinfo = "0.30"
egui_plot = "0.32.1"


